package charger

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/mark-sch/evcc/api"
)

func decorateGoE(base *GoE, chargePhases func(int) error) api.Charger {
	switch {
	case chargePhases == nil:
		return base

	case chargePhases != nil:
		return &struct {
			*GoE
			api.ChargePhases
		}{
			GoE: base,
			ChargePhases: &decorateGoEChargePhasesImpl{
				chargePhases: chargePhases,
			},
		}
	}

	return nil
}

type decorateGoEChargePhasesImpl struct {
	chargePhases func(int) error
}

func (impl *decorateGoEChargePhasesImpl) Phases1p3p(phases int) error {
	return impl.chargePhases(phases)
}
